### ISSUE TITLE
api docs are no longer served

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#103]
the docs were used to be accessible at `/docs`. I think we should make it accessible at `/api` and `/api/docs`

**Comment by sethvincent** [comment]
Just checked this and http://localhost:8181/api/docs/ is working.

<img width="690" alt="screen shot 2018-11-29 at 9 43 49 am" src="https://user-images.githubusercontent.com/164214/49240941-4cef8680-f3bb-11e8-8b72-bfa2255e590b.png">

**Comment by kamicut** [comment]
@sethvincent should we have them at `/api` ?
