### ISSUE TITLE
If a campaign_hashtag includes #, then clicking on the card goes to the main campaign page

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#116]
See http://localhost:8181/campaigns/#nctx

**Comment by alyssadelaine** [comment]
@sethvincent @kamicut Could one of you take this?

**Comment by alyssadelaine** [comment]
@kamicut This has since been resolved, correct?

**Comment by kamicut** [comment]
correct! campaign urls use the campaign project id instead of the hashtag
