### ISSUE TITLE
To-Do List Feature

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#127]
We are currently working on the following user workflow:

A user goes to the campaigns page and clicks on a project. There is a [button provided which reads "Add this campaign to your to-do list"](https://github.com/developmentseed/scoreboard/issues/119). When clicked, the chosen campaign is [added](https://github.com/developmentseed/scoreboard/issues/117) to the [`assignments` database table](https://github.com/developmentseed/scoreboard/issues/118). When the user goes to her dashboard, all campaigns she has added to her To-Do list are displayed in the [To-Dos section of her dashboard](https://github.com/developmentseed/scoreboard/issues/120).

Depending on user feedback, we may want to add the following:
* A user can mark a campaign on his To-Do list as "Completed". Completed To-Dos are visible in a separate tab from To-Dos In Progress.
* A team moderator or an admin can assign projects to users. We would need to add ways* to:
    1) Verify that user has the permissions to assign tasks to other users
    2) Display to the user ("User") which tasks were added by User and which were added by User's Admin or Team Moderator
    3) In the latter case, we should likely allow users to sort/filter their tasks by Assigner

\* Some of these have been started in @sethvincent's [branch](https://github.com/developmentseed/scoreboard/pull/121/commits/5f8f32f7fa3231f2f8d84eebbf3ce64bbf2561bc)

**Comment by LanesGood** [comment]
@kamicut does the to-do list feature exist in the Scoreboard schema? Or was this converted into the Campaign Assignments table?
