### ISSUE TITLE
Badge management lacks field for uploading badge icon

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#133]
There is no field for adding or updating an icon associated with a badge

**Comment by alyssadelaine** [comment]
The badge images we currently have are associated with metric categories (for example, "Waterways"), so we could use that to allow admins to choose which image they want to be displayed with their custom badge

**Comment by kamicut** [comment]
@alyssadelaine what are you thinking the component could look like for the badge icon selection?
