### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#15]
Right now scoreboard has a list of users with metadata and renders read-only users. We will be moving scoreboard to a login system. This has a few implications:

- Can stats be viewed by non logged in users?
- Are there different user permissions?
- Do we need to calculate stats for users that have never logged in?
- Do we have a public vs private profile where  certain stats are only available to the logged in user?

It would be good to talk through these issues @ricardomestre @geohacker @scisco @alyssadelaine

**Comment by kamicut** [comment]
Additionally, what does testing look like? Can we mock OSM users + their stats?

**Comment by kamicut** [comment]
Some notes:

# Why?

1. Users need to see some private information such as what tasks they should work on next
2. Users get more detailed insights into their mapping 
3. Logging in allows users to add personal data such as their affiliation to certain groups: country, team, company, etc. which enable different types of stats

# How?

## Backend

- Create a user table that can hold user information
  - Where should information related to user tasks go? Should this be abstracted such that we can tie any piece of information to a user id in the backend?

    ⇒ We could have a user API that allows getting/setting user info from background services such as "tasks assigned to user"

- For configurable user info such as "What country is the user from", we can have a configuration file that the scoreboard api can read that describes what user fields are
  - This could potentially get very complex so we need to figure out the use cases
  - Can an admin modify these fields at any time? If so these could be dynamically set as user "tags" in the database (similar to OSM tags). However the frontend needs to know what to render
  - How do we aggregate stats based on arbitrary user fields?
- Get ids and other profile information through OSM OAuth
- How are sessions handled? Should the frontend be session-less?

## Frontend

- Create a login / logout button
- Create a page for private "dashboard" of activity + tasks (what other information should this page contain?)
- Create a mechanism to update user information
- Change per country based statistics currently in scoreboard to read from the user database

**Comment by sethvincent** [comment]
closed by #28
