### ISSUE TITLE
Countries on dashboard

### ISSUE THREAD

**Issue by giblet22** [developmentseed/scoreboard#176]
On my user dashboard (I am an admin) I seem to have all countries listed, that should just be countries I've contributed to, correct?

![image](https://user-images.githubusercontent.com/7945333/49891272-1cc0d280-fe14-11e8-9db2-c32ebcf33721.png)

**Comment by kamicut** [comment]
@giblet22 that's interesting, yes it's supposed to be the countries that you've contributed to. We're fixing some bugs in the country code now so when we push some new changes we'll let you know to check again.

**Comment by giblet22** [comment]
@kamicut  I might have identified why I'm seeing all these countries, let me know once your country bugs are fixed, and if this seems to be the only instance, this could be considered closed.

**Comment by kamicut** [comment]
Thanks @giblet22, we made those modifications so I'm going to close the issue
