### ISSUE TITLE
Least Total Edits and Most Recently Edited each return users who have not yet edited

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#186]
Least total edit example:

<img width="1399" alt="screen shot 2018-12-13 at 4 06 03 pm" src="https://user-images.githubusercontent.com/6155420/49967556-38e67180-fef1-11e8-88f3-c23d838d965a.png">

Most recent edit example:

<img width="1372" alt="screen shot 2018-12-13 at 4 05 44 pm" src="https://user-images.githubusercontent.com/6155420/49967555-38e67180-fef1-11e8-8949-bdffa507c9b7.png">

**Comment by kamicut** [comment]
I think this can be solved using the NULLS LAST fix @sethvincent made here https://github.com/developmentseed/scoreboard/blob/bb678ea30ca92d776b5ed49d0b2cd3d36efce8a9/api/src/routes/users.js#L82

**Comment by scisco** [comment]
fixed
