### ISSUE TITLE
Add campaigns sort by creation and update dates

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#187]
Add ability to sort campaigns by creation and update time.

According to @kamicut:
> for tm2 and tm3 there is a way to get the created and lastUpdated time
for tm3 it's a bit harder, they don't give you the stats for all projects, you have to get it from each project individually

**Comment by kamicut** [comment]
I've started on this with a sort filter on the campaigns page. @LanesGood I'm wondering if we need some visual feedback in the cards for the dates:

![](https://kamicut-monosnap.s3.amazonaws.com/Mozilla_Firefox_2019-02-01_19-05-43.png)
