### ISSUE TITLE
Do we need to show the badge ID?

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#188]
It seems unnecessary:

<img width="843" alt="screen shot 2018-12-13 at 4 56 17 pm" src="https://user-images.githubusercontent.com/6155420/49970019-10ae4100-fef8-11e8-9c58-246128ec72a4.png">

**Comment by kamicut** [comment]
Hmm I wonder if we can show some other stat instead like number of users that have this badge?

**Comment by alyssadelaine** [comment]
Definitely agree @kamicut
I think we should make that functionality a separate issue as it would likely involve significant backend changes, since currently you only see a user's badges when you query that user's data directly
