### ISSUE TITLE
Single Team page

### ISSUE THREAD

**Issue by giblet22** [developmentseed/scoreboard#198]
Building off of #197 aggregate stats at a team level similar to how it's done for campaigns

ex.  Team A has mapped X buildings, Y coastlines, Z km of roads, etc

and be able to sort team members by edits

**Comment by LanesGood** [comment]
Currently proposed Teams table, borrowing from the Campaigns table:

| Rank | User | Campaigns | Roads(Km) | Points of Interest | Buildings | Railways(Km) | Coastlines(Km) | Waterways(Km) | Changesets | Edits |   |
|------|------|-----------|-----------|--------------------|-----------|--------------|----------------|---------------|------------|-------|---|

After conversations with @kamicut I understand teams statistics to be untied to teams - that is, we can't determine Km of Coastlines for a user's activity related to a team campaign, as there's no way to mark on a changeset that it should only be counted to a particular team.

However, I wonder if we can sort "Rank" within a team to see the highest contributors?

I also wonder if Campaigns is a useful statistic. Ideally, this would be the campaigns worked on by a user for that particular team. Unfortunately, I think this is also not possible at the moment, unless campaigns could be tagged with team names, and then teams read from those tags. 

@kamicut does the above sound correct to you?

**Comment by LanesGood** [comment]
@kamicut I've created the mockups below as two possible options. I think that while it could liven up the page, the user avatar introduces a risk of monotony given that very few users have a profile image. Both options incorporate a full team stats table, while v1 also includes some elements of the individual user dashboard.

v1
![TeamStats_v1](https://user-images.githubusercontent.com/12634024/69754714-9ab0e300-1124-11ea-94e1-6357678270ee.png)

v2
![TeamStats_v2](https://user-images.githubusercontent.com/12634024/69754715-9ab0e300-1124-11ea-8d49-79d18ba28ce8.png)

What do you think?

**Comment by kamicut** [comment]
I think this looks pretty good! I do prefer smaller avatar images. However, we could always create generated avatars to fill in missing profile images (we can detect this in the user profile request). In any case I think we can start work on the user tables for statistics and then figure out how to display the members.

**Comment by LanesGood** [comment]
@kamicut I've added back the "Team Scoreboard Panel" section into v2, posted below as v3. I'm aware that the "Active Campaigns" section may also not be possible, but we could change this to campaigns.

One additional idea: just one table with Members, rank, country, and total # of edits. Clicking an "Expand stats" button would then expose the feature counts for each member.

![TeamStats_v3](https://user-images.githubusercontent.com/12634024/70160850-28db1b00-1689-11ea-8230-24ac0193d950.png)

**Comment by LanesGood** [comment]
Single Team page should include:
- Team stats 
- Team members

For logged-in users who 1) have connected the Teams app, and 2) are members of the team:
- Team campaigns

For logged-in users who 1) have connected the Teams app, and 2) are moderators of the team:
- Edit team link

**Comment by LanesGood** [comment]
@guidorice for your reference, though posted in another issue, the single team page mockup can be found below.

![TeamPage_Connected](https://user-images.githubusercontent.com/12634024/77186915-08a16180-6aaa-11ea-9a7f-b80e0b2266b0.png)

**Comment by guidorice** [comment]
I deleted an outdated comment with mockup. Current mockup is in #526.

**Comment by guidorice** [comment]
This is partially implemented in #530. I am keeping this issue open for now to make sure we have  due diligence on what is actually possible as far as team statistics. Also to make sure all the user stories discussed above are actually implemented.

cc @giblet22 @LanesGood @kamicut

**Comment by guidorice** [comment]
Closing this and tracking the remaining features in #542, #544, #545 .
