### ISSUE TITLE
Remove "Recently Earned" badge

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#206]
We aren't tracking when a user earns each badge, so this section is confusing

**Comment by LanesGood** [comment]
@kamicut Looking at the brainstorm docs and user research, it seems like one of the main goals is to motivate new and experienced mappers. I'd like to suggest a "coming up" area that shows users what they can work on next (campaigns, map areas, badges) on the private profile. On the public profile I think some simple layout adjustments can boost the readability of the page.

**Comment by kamicut** [comment]
@LanesGood Correct, we want to motivate new mappers and move "coming up" features to the dashboard. The "Recently Earned" badge section on the public profile is a legacy component from before the split into public profile / dashboard. We can just remove it if we can't replace it with anything.

**Comment by alyssadelaine** [comment]
@LanesGood @kamicut 
So should we change "Recently Earned Badge" to "Upcoming Badge" and display one of the badges that progress has been made toward?

**Comment by alyssadelaine** [comment]
Fixed in https://github.com/developmentseed/scoreboard/pull/230
