### ISSUE TITLE
Completeness slider should measure "Complete" parameter

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#211]
@kamicut I remember us talking about how the Completeness slider measures a combination of "Complete" and "Validated", but it's confusing to set the "Completeness" range between 0 and 20 and see a 22% "Complete" campaign. I think we should add a slider for Validation

**Comment by kamicut** [comment]
This might increase complexity, but I agree the current way it is is confusing. The initial idea behind the formula to combine "complete" and "validated" was to remove the amount of fiddling with filters. Maybe a checkbox would filter out 100% complete campaigns to see only the ones that have less than 100% validated is better cc @giblet22

**Comment by giblet22** [comment]
What if there were two sliders, but only one could be toggled to work at a time, either complete or validated, that way it lets you filter but doesn't mess things up with having to deal with multiple filters? Just brainstorming

**Comment by alyssadelaine** [comment]
@giblet22 That's what I was thinking, and I think we could even apply the % Complete and % Validated filters at the same time. If the range selected is not feasible, like 85-100% validated and 0% complete, then we just wouldn't show any results
