### ISSUE TITLE
Scoreboard logo and favicon

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#213]
Right now the favicon for scoreboard is a generic symbol I got from the noun project. We should rethink what we want the favicon to look like, and whether we should have a logo for branding purposes.

**Comment by LanesGood** [comment]
HI @kamicut and all, I've created two logo options for Scoreboard, attached below for your consideration. The mockups also include a favicon preview, and the logo overlayed on the navbar. I think we would only want to use the logo in the navbar on a mobile view if at all, but mocked this up here just for reference.

![scoreboard_logoa](https://user-images.githubusercontent.com/12634024/50906221-a0a9b280-13f2-11e9-89f6-23be4bf3734d.jpg)

![scoreboard_logob](https://user-images.githubusercontent.com/12634024/50906222-a0a9b280-13f2-11e9-903e-26857f7e4a28.jpg)

**Comment by LanesGood** [comment]
Client decided on OptionA, closing issue
