### ISSUE TITLE
Add footer to all pages

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#216]
Footer design for platform needed. @LanesGood to provide visual design and component styles, and others (@kamicut ?) to implement in development upon approval.

**Comment by LanesGood** [comment]
Footer in progress. Current logos include: OpenStreetMap. Please see the attached, and let me know if there are any other necessary links/site info that should be included.

![scoreboard_footer](https://user-images.githubusercontent.com/12634024/50842222-3df1e180-1334-11e9-8cc6-bb51022fbe74.jpg)

**Comment by alyssadelaine** [comment]
Closed in https://github.com/developmentseed/scoreboard/pull/230
