### ISSUE TITLE
Add const Blurb to multiple pages

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#223]
I propose adding the "Blurb" text string from the individual Campaign page to multiple pages: the homepage, user dashboard, user profile, individual country pages, and individual team pages. This text should be located on the page directly below the [User Scoreboard Panel](https://github.com/developmentseed/scoreboard/issues/222) on all pages where that is present.

This text reads "{NUM}mappers, mapping {NUM} km of roads, {NUM} buildings, {NUM} Points of Interest, and {NUM} km of waterways."
```
const Blurb = ({
  users,
  km_roads_add,
  buildings_add,
  poi_add,
  km_waterways_add
}) => {
  return <h2 className='header--medium list--block'>
    {`${users.length} mappers, mapping
    ${km_roads_add.toFixed(1)} km of roads,
    ${formatDecimal(buildings_add)} buildings,
    ${formatDecimal(poi_add)} Points of Interest, and
    ${km_waterways_add.toFixed(1)} km of waterways.`}
  </h2>
}
```
This string should be dynamic, and I suggest that numbers be styled with classes to render the below.
<img width="657" alt="screen shot 2019-01-10 at 2 02 02 pm" src="https://user-images.githubusercontent.com/12634024/50990553-530b7380-14e0-11e9-80f3-4264e5ac13b4.png">

**Comment by LanesGood** [comment]
Page blurbs:

Country (individual):
`There are ${users.length} mappers in {$country.name}, mapping ${km_roads_add.toFixed(1)} km of roads, ${formatDecimal(buildings_add)} buildings, ${formatDecimal(poi_add)} Points of Interest, and
${km_waterways_add.toFixed(1)} km of waterways.`

User (individual):
`Since ${users.yearOfFirstEdit}, ${user.name} has mapped ${km_roads_add.toFixed(1)} km of roads, ${formatDecimal(buildings_add)} buildings, ${formatDecimal(poi_add)} Points of Interest, and
${km_waterways_add.toFixed(1)} km of waterways in ${user.countries.length} countries .`

User (dashboard)
`Since ${users.yearOfFirstEdit},  you have mapped ${km_roads_add.toFixed(1)} km of roads, ${formatDecimal(buildings_add)} buildings, ${formatDecimal(poi_add)} Points of Interest, and
${km_waterways_add.toFixed(1)} km of waterways in ${user.countries.length} countries .`

**Comment by kamicut** [comment]
Currently we do not have country data in OSMesa. We're implementing the blurb in #243 and will come back to this once we have the data
