### ISSUE TITLE
Badge spacing is off

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#229]
<img width="893" alt="screen shot 2019-01-10 at 5 50 24 pm" src="https://user-images.githubusercontent.com/6155420/51056832-e5c81300-15b1-11e9-8e9c-2dc8b6505fa6.png">

**Comment by LanesGood** [comment]
On this note, I'd ask you to look at my upcoming pull request for the badge
placement. I've widget-ized the badges and other parts of the site that
should look quite different from the current version.

**Comment by alyssadelaine** [comment]
@LanesGood If that PR will close this issue, you can put `Closes 229` in the first comment of your PR and it will close this issue automatically when it is merged
