### ISSUE TITLE
Users Can Print a Badge Certificate 

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#255]
As proposed by client: when a user achieves a badge on Scoreboard they should be able to print a certificate showing their achievement. Certificate may also be printed by Admin, and can show all badges a user has earned.

Proposed implementation: a button below the "Earned Badges" section that generates the HTML of one of certificate options below, with a print media CSS stylesheet.

![certificatedraft1](https://user-images.githubusercontent.com/12634024/52135009-dec17d00-2612-11e9-863f-76fea0933062.png)
![certificatedraft2](https://user-images.githubusercontent.com/12634024/52135088-0b759480-2613-11e9-9a65-9c6c68b77185.png)

**Comment by alyssadelaine** [comment]
@LanesGood 

Can we remove "Signed" from the second option, and make the background white? We may also want to remove the line under <Name> so we don't need to worry about it looking strange for longer names.

On the first option, let's remove the other badges; there may be too many to list

**Comment by LanesGood** [comment]
@alyssadelaine I thought the "all badges" option was discussed as a client request. I suggest we include a version with and one without. The "all badges" could also be it's own separate printout

**Comment by LanesGood** [comment]
@alyssadelaine see the attached for your review/sending for approval

![certificatedraft2](https://user-images.githubusercontent.com/12634024/52236853-ff4d3980-2895-11e9-8bd5-cbc046f72d6d.png)
![certificatedraft1](https://user-images.githubusercontent.com/12634024/52236855-ff4d3980-2895-11e9-8ecb-124fdcabafe3.png)
![certificatedraft3](https://user-images.githubusercontent.com/12634024/52236856-ff4d3980-2895-11e9-8aee-333777d9a2b7.png)

**Comment by alyssadelaine** [comment]
Oh right @LanesGood I was thinking all badges as separate -- I like the way you have it here
