### ISSUE TITLE
"Since NaN, ..."

### ISSUE THREAD

**Issue by mojodna** [developmentseed/scoreboard#269]
![image](https://user-images.githubusercontent.com/45/52303395-b7392000-2944-11e9-9b59-84e47ddc4656.png)

**Comment by kamicut** [comment]
Thanks for reporting @mojodna. @LanesGood this happens if a user has no stats. What should we display in the blurb?

**Comment by mojodna** [comment]
Also worth hiding if a user hasn't contributed to any campaigns?

![image](https://user-images.githubusercontent.com/45/52303498-02533300-2945-11e9-96cf-dc5e36312cf3.png)

**Comment by mojodna** [comment]
Err, and probably other things. Blank slates are hard.

**Comment by LanesGood** [comment]
@kamicut Can this conditionally display something like "You haven't mapped any features in {environment name} yet - contribute to campaigns(link) to get started!" ?

As for the campaign tables, I would suggest that we do not render this component for users who have no favorites, assigned campaigns, or contributions.

**Comment by LanesGood** [comment]
Closed by #467 for Dashboard. 

The issue of an empty page still exists for public profiles - this will be noted in a separate issue
