### ISSUE TITLE
Should campaign completeness mirror the tasking manager?

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#277]
## tm2

Currently for tasking manager v2, the completeness field we get from the API is the "area done" parameter. When a campaign is completely mapped and completely validated, the response from the TM2 API is 0% `done` and 100% `validated`, and our campaign cards show a completeness of 0% and 100% validated. 

cf [Relevant lines in TM2](https://github.com/hotosm/osm-tasking-manager2/blob/281eb61a98ca6a70e2baa5231cab88abf7e434e2/osmtm/models.py#L617-L651)

## tm3
In the TM3, we use `percentMapped` and `percentValidated`. For a completely mapped campaign `percentMapped` is 100% and `percentValidated` is 100%. Thus our campaign cards will show 100% completeness and 100% validated.

## What should completeness measure? 
Should it be:
1. Percent of total tasks that are mapped 
2. Percent of total tasks mapped but that are not validated 
3. A combination of area mapped and validated that creates a completeness "measure" 

cc @alyssadelaine @LanesGood

**Comment by alyssadelaine** [comment]
@kamicut Could we just enforce that 100% validation -> 100% complete?

**Comment by alyssadelaine** [comment]
@kamicut So should we add a check for ^?

**Comment by kamicut** [comment]
@alyssadelaine since in TM2, completeness is area done, it feels like we should check for the version and calculate something like completeness = (done + validated) / 2. For tm3 we don't need to change anything

**Comment by kamicut** [comment]
After discussing with @LanesGood, we will change the wording of complete to "Mapped". For TM2, we'll count `mapped = validated + done`, and keep TM3 the same.
