### ISSUE TITLE
Edge case crashes the dashboard

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#307]
If a user:

- [x] Is on Firefox
- [x] Has 0 edits
- [x] Has WebGL disabled

then the dashboard crashes when trying to render the Leaflet map

**Comment by LanesGood** [comment]
I'm unable to reproduce this bug, following all steps above. Given that we've not measured this elsewhere, I'm closing this issue. Will reopen if ever we hear of the bug resurfacing.

See below:
![Screen Shot 2019-10-31 at 12 27 43 PM](https://user-images.githubusercontent.com/12634024/67966247-f053a780-fbd9-11e9-9750-c47ec255a725.png)
![Screen Shot 2019-10-31 at 12 27 53 PM](https://user-images.githubusercontent.com/12634024/67966249-f053a780-fbd9-11e9-8a36-6571fdcad9e2.png)

**Comment by alyssadelaine** [comment]
@LanesGood Yeah I'm sure work has occurred on webGL and other features since this that may have resolved this error
