### ISSUE TITLE
Terms link in the footer leads to a 404

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#312]

**Comment by alyssadelaine** [comment]
@LanesGood @kamicut Can we remove this if there are no terms to link to?

**Comment by LanesGood** [comment]
Absolutely - my mistake including this placeholder without a real link. Are
there any guidelines/terms/agreements on the client side that could or
should be linked here?

**Comment by alyssadelaine** [comment]
Not that I know of, though we should probably have some. Let's delete the link for now and I'll create that as a separate issue

**Comment by alyssadelaine** [comment]
This was resolved
