### ISSUE TITLE
"Assigned by" column is confusing when all campaigns are displayed

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#335]
Showing campaigns I participated in as "Assigned by [me]" is confusing. 

Here is the view of all campaigns contributed in with a set of test data:

![image](https://user-images.githubusercontent.com/6155420/55339706-33497300-5471-11e9-8bb4-07232e8106d4.png)

And here is the list of campaigns which were actually favorite-d:
![image](https://user-images.githubusercontent.com/6155420/55339834-73105a80-5471-11e9-9159-25021d8cecc3.png)

I am open to other suggestions, but one option would be to remove the "Assigned by" column and replace it with "Status", which could read "Participated" or "Assigned by [assigner]"

**Comment by LanesGood** [comment]
@alyssadelaine and I discussed and have expanded this issue. Beyond the confusion of the "Assigned by" with the user's own name, there should be a table tab with the user's own campaign contributions highlighted. We arrived at the following solution:

New User Campaigns table tabs:
Assigned | Favorites | Contributions | All


New "All" table column headers:
Name | Sources | Priority

**Comment by LanesGood** [comment]
@alyssadelaine I've created a draft PR with the initial commit. I did not successfully add a new column in all with "sources" referring to the campaign's parent category. Blockers = javascript 

Additionally I discussed with @kamicut, and his thoughts are:
- Drop "all" as a category
- Make assignments the default tab
- Open separate ticket for a notification center/mechanism to surface the projects that are "new" - assigned but not contributed to yet.

I think all of this is getting into an area that would be best to validate with our partners.

**Comment by alyssadelaine** [comment]
Hey @LanesGood , remember that we talked about dropping all as a category, but decided that it would be best to leave it as the default so that if a user receives a new team assignment or adds a favorite, they will see that change reflected immediately in their dashboard.

I don't think we need the notification center option yet, though you can feel free to open a ticket for it.

This was a request from me because the old set of columns didn't make sense once we expanded the data to be "all campaigns". Could you and @kamicut pair to finish this up tomorrow?

**Comment by LanesGood** [comment]
Implemented in #342, closing
