### ISSUE TITLE
Advanced Panel Design Edits

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#343]
Let's have the Advanced panel be hidden by default:

**> Advanced** 

with an option to expand, i.e.,

**V Advanced**
[ Proxy URL options ]
[ Parameter options ]

**Comment by alyssadelaine** [comment]
I also noticed the spacing in the [Query Parameters panel](https://github.com/developmentseed/scoreboard/pull/314) is a bit off:

![image](https://user-images.githubusercontent.com/6155420/56240089-8cfc9080-6060-11e9-88b1-15d0896b6182.png)

@LanesGood Could you make that a bit more uniform once it's merged in?

**Comment by LanesGood** [comment]
@alyssadelaine thanks for noting these issues, I've added these to #314
