### ISSUE TITLE
Investigate tight integration with OSMesa stat server

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#349]
Right now Scoreboard gets stats from OSMesa using the [osmesa-stat-server](https://github.com/azavea/osmesa-stat-server). In order to do some more interactive statistics such as “How many users would get this badge if I created it?” we would need a tighter integration with the database (and possibly arbitrary queries). We could do this by connecting to osmesa-stat-server’s database on the application side. [Foreign data wrappers](https://wiki.postgresql.org/wiki/Foreign_data_wrappers) could also be useful to investigate. cc @alyssadelaine @mojodna

**Comment by mojodna** [comment]
The easiest way is probably to connect directly to the Postgres instance containing aggregate stats.

**Comment by kamicut** [comment]
@mojodna I think that's right if we're doing the logic on the server side, but would like to see if there's a way to do a query like "select edits from `osmesa` for users in (select members from `scoreboard` where teamid = x)" without a lot of data shuffling.

**Comment by jpolchlo** [comment]
I agree that co-locating tables for both applications on the same PG instance is the way to go, with the understanding that we maintain separate "ownership" of the tables therein.  Read from any table you want, but edit only your own.  That may be implicit in your thinking, @kamicut, but doesn't hurt to be clear about it.

**Comment by kamicut** [comment]
@jpolchlo well there's two ways of doing this, and I think that merging the two databases might be the best in terms of performance, but difficult in terms of separation of concerns, and update cycles. @mojodna is right that the easiest is to connect to two databases from the node server on our side. I'm wondering if `postgres_fdw`[1]  will be a good compromise, because my intuition is that doing 2 queries on the server and merging the data will be slower than doing it in the database.

[1]: Here's an article I am reading about `postgres_fdw` https://www.percona.com/blog/2018/08/21/foreign-data-wrappers-postgresql-postgres_fdw, I've never used it so if you have experience with this pg feature your opinion would be appreciated

**Comment by mojodna** [comment]
I've also never used it, but have heard that it works quite well. However, is it over-complicating the solution?

@kamicut can you write up a specific use-case listing the necessary raw aggregates from the OSMesa side?

**Comment by LanesGood** [comment]
This is now done via #426 #432 and #434
Thanks @kamicut and @sethvincent !
