### ISSUE TITLE
Scoreboard should not depend on OSMESA or OSM Teams

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#358]
I think we should have some kind of mechanism to turn teams and OSMesa on or off, maybe in the Admin page (also making the services configurable). We should also make sure that pages render even when those services are unreachable. Right now if the services are unreachable there are errors in the console. 

This also leads us to think: what would a scoreboard without osmesa stats or osm-teams look like? Would it be bare or would there still be some functionality?

**Comment by LanesGood** [comment]
@kamicut does PR #468 address the configuration part of this? If so lets add a "contributes to" line in the PR description.

**Comment by kamicut** [comment]
@LanesGood what do you mean by a contributes to line?

**Comment by guidorice** [comment]
> This also leads us to think: what would a scoreboard without osmesa stats or osm-teams look like? 

Yes, that's what I thought when I read this. I suggest closing this issue until there is a clearer picture of what this enhancement would be about.

**Comment by kamicut** [comment]
Should we close this @LanesGood

**Comment by LanesGood** [comment]
Closing, can re-open if interested parties propose a clear view of this enhancement.
