### ISSUE TITLE
Attainable badges should be moved to dashboard

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#36]
Now that we have attainable badges given by the server https://github.com/developmentseed/scoreboard/commit/12694e90903ed587aed9cfedc754479b3110c18d we can now split badges depending on the person logging in. Now we could build a dashboard with "badges to earn" and move them off of the public profile @sethvincent

**Comment by sethvincent** [comment]
The dashboard now has a section for attainable badges. They haven't been removed from the public profile yet. I wonder if seeing "in progress badges" on the public profile would still be useful, though.
