### ISSUE TITLE
Distinguish between edits and changesets in variable names

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#373]
We broadly use the term "edit" in variable names to refer to both edits and changesets, and it has caused confusion that has permeated the frontend and user experience. We should update the code to separately and accurately reference these different statistics.

**Comment by LanesGood** [comment]
With the updated schema and previous changes, there are no longer cases of "edit" in variable names referring to changesets. Closed by #346 and #387
