### ISSUE TITLE
Campaign Table displays added + modified coastlines, but CSV download only includes added ones

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#375]
Relevant lines: https://github.com/developmentseed/scoreboard/blob/701015a9949779a04511293873ad0fbdc50b725e/components/campaign/CampaignTable.js#L44-L59

**Comment by LanesGood** [comment]
@alyssadelaine re: campaign table headers
I also see that the Edits/Changesets column still has some work needed here. It looks like in #346 you kept `editSum`, but `develop` has no data for this in the Campaigns table. Is the `editSum` property deprecated, or should it be labeled differently? And is the table correctly distinguishing between Changesets and Edits?

**Comment by alyssadelaine** [comment]
@LanesGood That was updated [in this PR](https://github.com/developmentseed/scoreboard/pull/374/files)

**Comment by LanesGood** [comment]
@alyssadelaine I see the [relevant line changes](https://github.com/developmentseed/scoreboard/blob/4d51d56e9e5b0a09eac66b566c7773db61354672/components/campaign/CampaignTable.js#L47) in the new codebase, but `editsSum` returns `0` - this is visible on all the individual campaign page tables and in the download.
![Screen Shot 2019-05-30 at 4 18 43 PM](https://user-images.githubusercontent.com/12634024/58661735-9c752780-82f6-11e9-991d-771da3b257a5.png)

I see `edit_count` and `edits` in the user object - are we waiting on a change on this from the OSMESA side?

**Comment by alyssadelaine** [comment]
That is not what shows up for me locally (pictured) or on the staging server
![image](https://user-images.githubusercontent.com/6155420/58661931-11486180-82f7-11e9-8114-b6f5de68ceae.png)

**Comment by LanesGood** [comment]
@alyssadelaine all good now, fixed with a restarted local server
