### ISSUE TITLE
UI tooltip for stats

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#380]
Certain headers and labels could have a tooltip to explain how the statistic was calculated. For example in the campaigns page, if we hover over the Roads (KM) header, we would want to display that the statistic is kilometers of roads added + modified.

**Comment by LanesGood** [comment]
@necoline implementing a tooltip for the platform with some level of abstraction would be a great enhancement. Is this something you can take a look at? On a basic level, this could simply be implemented on the page itself. I'm curious if there is also an abstract method we could use to have a single file with definitions provided to tooltips throughout the app.

**Comment by necoline** [comment]
We could definitely add that in. If there is a limited number of definitions, we can hold those values in an enum util and implement it wherever we want in the app. I can create the tooltip components and then maybe we can map out where we want to implement the tooltip and what values it requires.

**Comment by kamicut** [comment]
closed in #427
