### ISSUE TITLE
Page blank state

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#382]
Most pages in Scoreboard load in with the global header and footer, but no content. This results in a flash of the footer before the page content loads in, which is disorienting and distracting as a user. 

A blank state for pages can alleviate this distraction and reinforce the perception of speed and performance. There are a few different categories of pages that will require their own blank state, depending on implementation. 

For the homepage, admin page, user dashboard and profile a minimum height on the page content can help with the footer flash. However, this could be disadvantageous on shorter pages that use this min-height. It has no effect on the users/countries/campaigns pages. 

Blank states needed:
- Internal page header + header content
- Tables for users, countries, teams
- Admin cards
- Stats panel

_The below are gifs of pages loading at 25% actual speed:_

**Home**
![sb_home-slow](https://user-images.githubusercontent.com/12634024/59003716-128cf900-87e5-11e9-8a8a-1d1d91c4511d.gif)

**Admin**
![sb_admin-slow](https://user-images.githubusercontent.com/12634024/59003742-2a647d00-87e5-11e9-8e90-6330575f9184.gif)

**Users**
![sb_users-slow](https://user-images.githubusercontent.com/12634024/59003752-33ede500-87e5-11e9-87a8-f28a6d63b255.gif)

**Dashboard**
![sb_dashboard-slow](https://user-images.githubusercontent.com/12634024/59003765-40723d80-87e5-11e9-84c3-4ed575638bfd.gif)

**User Profile**
![sb_user-slow](https://user-images.githubusercontent.com/12634024/59003798-613a9300-87e5-11e9-8dfc-0f6090af9094.gif)

**Campaign**
![sb_campaign-slow](https://user-images.githubusercontent.com/12634024/59003805-67307400-87e5-11e9-9392-4a39bda035b3.gif)

/cc @kamicut

**Comment by guidorice** [comment]
@LanesGood it's really cool how you illustrated this problem using the animated gifs! I was just noticing the same issue on the `/users` route where it shows all zeros while loading.

**Comment by guidorice** [comment]
@LanesGood is this still work-in-progress or good to close issue?
