### ISSUE TITLE
Filter projects that are named 'Untitled Project' 

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#400]
We should filter out projects that are titled 'Untitled Project' from the tasking manager since they are likely to be abandoned drafts or archived projects.

**Comment by LanesGood** [comment]
**Done:** 
- Removed projects with no edits
- Projects with no `title` but with edits are still displayed in Scoreboard

**To Do**
- Address Untitled Projects as part of refactoring campaign sync/enhancing admin privileges #393
