### ISSUE TITLE
Sortable Columns

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#438]
Add the ability to sort the columns in the campaign tables. I'm thinking of using [react-table](https://github.com/tannerlinsley/react-table) for this.

**Comment by kamicut** [comment]
A little trickier than I thought, because of the new work on the glossary. Here's my thought process:

- React Table's `useTable` hook needs a Column and Data array that are sent down to the props to build the table headers
- We have a separate component that builds the table headers to include the tooltip and glossary
=> Use the ability to turn the Header of the Columns prop (https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#column-options) into a function to dynamically build the Header prop, injecting the tooltip

**Comment by LanesGood** [comment]
@kamicut we should address the design constraints here. With the new tooltip icon, and the additional stats, there is far less space for the table. Adding the icon for sorting will make this even more cramped. I think the default sort functionality in react-table is too hidden, and would recommend we use a version of a sorting icon. 

One basic option: remove the max-width for the table's parent wrapper, and allow this to be almost full-width on large screens. For smaller screens, we can set a wider fixed width on table columns. We could also explore a toggle for displaying sort options, or even build in some of the considerations of #406 

I'm happy to jump in on the PR for styling when its ready.

**Comment by LanesGood** [comment]
Closed by #441. Design issues mentioned above to be addressed separately.
