### ISSUE TITLE
Table Pagination lists empty pages

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#449]
Even with 0 table rows, all paginated table list many more pages than there are actual rows:
![image](https://user-images.githubusercontent.com/12634024/69648238-e4bc9a80-1038-11ea-9a94-bc13e4193e12.png)

Users can navigate to these empty pages:
![image](https://user-images.githubusercontent.com/12634024/69648266-f43be380-1038-11ea-9e19-75abbdf7b2ef.png)

The max number of pages seems to be set at the max number of items. Table pagination should reflect sorted and filtered tables, and only display numbers for the pages of actively filled items.

**Comment by kamicut** [comment]
To replicate, do a simple filter by country on the all users table. The pagination and total results returned are off, showing this problem.
