### ISSUE TITLE
Split into seperate repos

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/scoreboard#45]
We'll likely need to create separate repos rather than have the api and frontend in one repo.

I'd probably split them into:

- scoreboard-api
- scoreboard-ui
- scoreboard-deploy

**Comment by kamicut** [comment]
@sethvincent why would you want to split the repos? We moved to using `lerna` to stick with one repo cc @scisco

**Comment by sethvincent** [comment]
closed by #62 where we went the opposite direction and made the api and ui one deployment rather than keeping them separate.
