### ISSUE TITLE
Develop branch won't build; Upgrade Node version to latest LTS 12.x?

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#469]
Currently the develop branch won't build for me because the `file-loader` package now requires node >= 10. This is a breaking change  mentioned in `file-loader` 5 release notes.

- [ ] ideally we can bring node specified in `.nvmrc` to latest LTS version (12.14.1)
- [ ] does this work with circleci? any changes required to deploy images?
- [ ] does this work with deployment environments? any changes required to deploy images?

Also note a quick fix (untested) should be:

- Change `file-loader` dependency to be < 5.0

kamicut says:

> locally i use file-loader~2 and we can fix it at that version for now

**Comment by kamicut** [comment]
woops forgot to modify .nvmrc

**Comment by guidorice** [comment]
@kamicut in addition to the .nvmrc, the README also mentions a node version.

**Comment by guidorice** [comment]
@kamicut do you agree the .nvmrc and readme needs to be updated to 12.14.1 to match this commit?

https://github.com/developmentseed/scoreboard/commit/8708fcee0d88db1870091a9f5e563f198a6ef2ab

I am happy to do this but wanted to confirm with you first.
