### ISSUE TITLE
Update Teams Settings in admin panel

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#480]
To properly implement the moderator role specified in #460, the team management screens should be ~removed~ updated from the admin panel, thus separating concerns properly. 

_Fill this issue in with more details on implementation and UI as needed_

**Comment by LanesGood** [comment]
After creating the mockups in #485 I think the Admin interface change for Teams is quite simple. The "Connect Teams" button is still needed and appropriate in the Admin interface, as this is a back-end app-wide control. However, Admins do not need the `See All Teams` or `Create Team` options in the interface, as these are now available in the Teams Page.

So the "Connect Teams App" button could be moved to Settings - either made immediately obvious in the widget like in the screenshot below, or as a prominent option on the Settings page.

![image](https://user-images.githubusercontent.com/12634024/73030382-824d0400-3e07-11ea-9aaf-d6714a860e07.png)

What do you think @kamicut @guidorice ?

**Comment by kamicut** [comment]
@LanesGood Connect Teams App is not an app-wide setting, it's a per-user setting. That means moderators will also have to "Connect Teams" so that they can view their private teams managed by OSM Teams.

**Comment by LanesGood** [comment]
@kamicut thanks for the clarification. As discussed, I'll explore adding the "Connect Teams" button to the general Teams page for each individual user, and post mockups to the appropriate issue shortly.

**Comment by LanesGood** [comment]
Update: the Teams widget should be removed completely from the Admin interface. The Connect Teams button is exposed elsewhere as covered by #501

**Comment by LanesGood** [comment]
Closed by #508
