### ISSUE TITLE
Link for "Explore active campaigns to get started" does not use correct prefix

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#484]
In staging environment, we noticed following this link results in a 404 not found error

> (username) has not made any mapping edits in yet. Explore active campaigns to get started!

Consider using overloaded link component here instead.

**Comment by guidorice** [comment]
I think it can be resolved by changing the `a href` to a `<Link href...>` component. That is how other nav links appear to be working.

**Comment by LanesGood** [comment]
Fixed in #492
