### ISSUE TITLE
Campaigns CSV export does not have `.csv` filename extension

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#491]
On OS X 10.15, it fails to open in the spreadsheet app unless I first save and rename the file to something.csv.

Note: this problem does not occur with the users/id Export Data button, where the file correctly has a .csv extension.

<img width="554" alt="Screen Shot 2020-01-28 at 1 28 45 PM" src="https://user-images.githubusercontent.com/766758/73302620-23560900-41d2-11ea-9c37-1110ebb08c14.png">

<img width="532" alt="Screen Shot 2020-01-28 at 1 20 11 PM" src="https://user-images.githubusercontent.com/766758/73302555-091c2b00-41d2-11ea-9fca-6ed5f39a97ef.png">

**Comment by LanesGood** [comment]
Fixed in #490
