### ISSUE TITLE
Action item: security alerts for docusaurus/website/yarn.lock

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#496]
In https://github.com/developmentseed/scoreboard/network/alerts
there are several security alerts for `docusaurus` dependencies. 

I propose dismissing them with "risk is tolerable to this project" because docusaurus is basically a static site builder and all the content+inputs are curated and under source control.

@kamicut is this OK with you?

**Comment by kamicut** [comment]
I agree with you, go ahead.

**Comment by guidorice** [comment]
I dismissed these alerts with  "risk is tolerable to this project"


- set-value
- underscore.string
- js-yaml
- remarkable
