### ISSUE TITLE
Rewrite frontend APP_URL

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#50]
I am reposting from #38 

This line in https://github.com/developmentseed/scoreboard/blob/master/frontend/src/containers/Dashboard.js#L141 (and others around the app) does not make sense when hosting a public version of scoreboard. We should rewrite localhost:5000 either:

- Rewrite APP_URL on the server and render the page on the server (this is the simplest logic)
- Create a frontend REACT_APP_URL that replaces this at build time (this is the simplest fix, but requires two environment variables, APP_URL on the server and REACT_APP_URL on the frontend) cc @sethvincent

**Comment by sethvincent** [comment]
I agree. At minimum we need config for the frontend that makes the api url `localhost:5000` configurable for deployments.

**Comment by kamicut** [comment]
@sethvincent do you prefer any particular approach?

**Comment by sethvincent** [comment]
Let's go with using the `REACT_APP_URL` env var on the frontend.

**Comment by kamicut** [comment]
This will be handled by https://github.com/developmentseed/scoreboard/pull/62

**Comment by sethvincent** [comment]
closed by #62
