### ISSUE TITLE
Create team

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#504]
Users who have signed in and integrated the Teams application via Connect Teams #501 are able to Create Team from the Teams index page.

Create Team enables the addition of all existing information of a team, including:
- Add team name, hashtag, description, location

**Comment by guidorice** [comment]
Reopening because the user story is not complete, and we do not know if the above mockup is captured anywhere else.

**Comment by LanesGood** [comment]
Noting that the above mockup is also captured in #485 earlier in the comment thread

**Comment by kamicut** [comment]
Closed in #509
