### ISSUE TITLE
Edit Team from Scoreboard

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#505]
Team moderators who have connected the Teams application to Scoreboard can edit and moderate a team from within Scoreboard. This includes:
- Edit Team hashtag, location, description
- Add/remove members
- Promote/demote moderators

**Comment by guidorice** [comment]
@LanesGood @kamicut this issue may depend on changes to osm-teams api. I will link any new or existing osm-teams issues to this issue.
