### ISSUE TITLE
Team Moderators can assign campaigns

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#506]
In Scoreboard, users who are also Team Moderators can assign campaigns to a team. This should first be enabled in the "Edit Team" screens in #505. Future enhancements may see this enabled on individual campaign pages.

**Comment by LanesGood** [comment]
Teams need an "assigned campaigns" table.

Team moderators should be able to add and remove campaigns to the team's assignments table.

Team moderators should be able to set the priority of each campaign (Low, Med, High)

Campaigns assigned by teams should be included in users' Campaigns tables exposed on the dashboard.

**Comment by guidorice** [comment]
Closed by #505
