### ISSUE TITLE
Teams page: Inconsistent UI states

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#511]
I am seeing really inconsistent UI states, which seems (I am guessing) to depend on whether the page is SSR or accessed via the nav bar:

Teams Page after reloading URL:

<img width="1785" alt="Screen Shot 2020-02-26 at 8 45 35 AM" src="https://user-images.githubusercontent.com/766758/75361368-6dcfb180-5874-11ea-8ee3-c3632b845962.png">

Then click on Scoreboard in navbar to return to homepage, then click on Teams in navbar:

<img width="1785" alt="Screen Shot 2020-02-26 at 8 45 39 AM" src="https://user-images.githubusercontent.com/766758/75361484-98216f00-5874-11ea-8f0f-91df2676911e.png">

Possibly relates to #510 
Definitely relates to #508

**Comment by guidorice** [comment]
<img width="1753" alt="Screen Shot 2020-02-26 at 5 21 10 PM" src="https://user-images.githubusercontent.com/766758/75400419-7350ea00-58bc-11ea-9167-5b953d36f754.png">

- ^ here is another inconsistent state: I clicked logout in Scoreboard, but Scoreboard still thinks it's connect to osm-teams (indeed maybe it is... but what does that technically mean, and what should the user think?).

- There is no way to disconnect from osm-teams once it's connected.

- For the osm login there are symmetrical login/logout buttons, which makes sense.  For the teams integration I think there also needs to be a way to disconnect from osm-teams (e.g. add a disconnect button) Not only will this make development easier, it would perhaps support the use case of an admin wanting to connect scoreboard to a different osm-teams deployment after some users have already connected.

**Comment by guidorice** [comment]
Another inconsistent UI state I saw today was `http://localhost:8181/teams` showed both my list of 2 teams, and in addition it showed the "Connect Teams" banner and action button. Apparently it thought I needed to connect to Teams but yet it somehow got a list of teams. Maybe some kind of race condition between hitting the teams api and rendering the page? I did not get a screen capture of this situation unfortunately.

**Comment by guidorice** [comment]
> For the teams integration I think there also needs to be a way to disconnect from osm-teams (e.g. add a disconnect button

See existing issue #391

**Comment by guidorice** [comment]
I deleted 2 of my comments on this issue which  had to do with public teams being displayed, even if I have not clicked the "Connect your Teams" button. This is the expected behavior. Public teams will always be shown. Private teams will only be shown after Connecting with osm-teams.

**Comment by kamicut** [comment]
For a short term solution, I think we can force server side rendering from the nav bar by replacing <Link> to simple anchor tags.

**Comment by guidorice** [comment]
The Redux devtools show that the store still has the correct data in `teams.records`. So this may not be a CSR vs SSR rendering issue after all.
