### ISSUE TITLE
Unlink Tasking Manager

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scoreboard#55]
I think that tasking manager should not be coupled to scoreboard tightly. We should move towards the concept of "Adding a task" and we could add tasks from multiple sources, such as a TM2 or a TM3 instance. These tasks could then be assigned to teams.

**Comment by kamicut** [comment]
This is currently being worked on as part of #67

**Comment by kamicut** [comment]
@alyssadelaine could you update the progress on this issue so far?

**Comment by alyssadelaine** [comment]
@kamicut I'm going to close this in favor of https://github.com/developmentseed/scoreboard/issues/67 since I've already put my notes there
