### ISSUE TITLE
[Teams] Fix filters for own/moderated teams

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#571]
The checkbox filters for Teams are not working: 

1. "Only show teams I'm a member of." is not clickable and needs to be fixed.
2. "Only show teams I moderate." is clickable, butt does not affect the teams listing.

![image](https://user-images.githubusercontent.com/12634024/80995633-917f1d00-8e0c-11ea-8838-84922d695986.png)

**Comment by guidorice** [comment]
I cannot reproduce this bug in development mode. However, the next.js production build  reproduces the bug, both on both the staging server and running locally. There is a Js exception:

<img width="841" alt="Screen Shot 2020-05-04 at 2 34 34 PM" src="https://user-images.githubusercontent.com/766758/81011054-84fec280-8e14-11ea-8b06-565ae647fb7c.png">

**Comment by guidorice** [comment]
I am now seeing a different error in development mode though:

```
TypeError: _this$state$user$acco is null
handleFilters
./pages/teams.js:152

  149 |   this.handleFilters({ searchText, onlyMemberTeams, onlyModeratedTeams })
  150 | }
  151 | 
> 152 | handleFilters ({ searchText, onlyModeratedTeams, onlyMemberTeams }) {
  153 |   const { user: { account: { id: osmId } = {} } = {} } = this.state
  154 |   let { teams: { records: teams } } = this.props
  155 |   if (searchText) {

handleOnlyMemberTeamsToggle
./pages/teams.js:133

  130 | handleOnlyMemberTeamsToggle (e) {
  131 |   const onlyMemberTeams = e.target.checked
  132 |   const { onlyModeratedTeams, searchText } = this.state
> 133 |   this.handleFilters({ searchText, onlyMemberTeams, onlyModeratedTeams })
  134 |   this.setState({ onlyMemberTeams })
  135 | }
  136 | 
```

**Comment by guidorice** [comment]
The root cause seems to be problems transpiling default values in destructuring objects, for example.

```js
    const { user: { account: { id: osmId } = {} } = {} } = this.state
```

Changing to use Ramda `pathOr` fixes it.
