### ISSUE TITLE
Queue is not defined

### ISSUE THREAD

**Issue by jvntf** [developmentseed/scoreboard#591]
Seeing this error and having trouble identifying the cause. Error appears on access of `/campaigns`

![image](https://user-images.githubusercontent.com/19439427/89656082-0ee97c00-d899-11ea-80f6-736a9d1d830f.png)

**Comment by jvntf** [comment]
The issue does have to do with some incompatible versions but I'm not sure which. solved by restoring the lockfile from a working version.

**Comment by guidorice** [comment]
@jvntf can you clarify what you mean by restoring the lockfile? If the `yarn.lock` is incorrect in the development branch, than that's a problem we should definitely address in a PR.

**Comment by jvntf** [comment]
this is fixed now @guidorice
