### ISSUE TITLE
Need documentation on osm-fabricator dependency, and how to develop on it.

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#599]
### Background

Scoreboard depends on [osm-fabricator](https://github.com/developmentseed/osm-fabricator) and uses it in it's docker-compose.yml like this:

```
  osmesa:
    image: developmentseed/fabricator:latest
    ports:
      - 5434:5432 
```

If you don't have a local image with that tag, docker will pull from dockerhub this image

```
developmentseed/fabricator        latest                     fdec21b59399        10 months ago       714MB
```

Inspecting that image, it contains some data:

```
docker run -p 5432:5432  developmentseed/fabricator:latest
psql postgres://postgres@localhost/postgres  -c "select count(*) from changesets"
 count 
-------
  6599
(1 row)
```

### Problems

- The dockerhub image  may not be up-to-date with what scoreboard is expecting, or what the osm-fabricator 's scripts are currently producing today if you run them locally.

- If you follow the readme in osm-fabricator repo, it's not clear at all steps needed to be done to get it to show up in scoreboard.

Relates to https://github.com/developmentseed/osm-fabricator/pull/2
Relates to https://github.com/developmentseed/scoreboard/pull/593

cc @jvntf

**Comment by guidorice** [comment]
I am proposing in addition to documenting this better, we remove the image  `developmentseed/fabricator:latest` from dockerhub, so as not to have stale data or outdated db schema sitting out there.

cc @jvntf @kamicut ,

**Comment by jvntf** [comment]
@guidorice i think it makes sense to make fabricator a local dev dependency. but yes we for sure have to add to the documentation about how to make scoreboard look for the local image.
