### ISSUE TITLE
View all users link is broken on front page

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#80]
![screenshot 2018-11-28 13 47 42](https://user-images.githubusercontent.com/1933118/49174387-33473400-f314-11e8-9b6f-0c8c7b31fb36.png)

**Comment by sethvincent** [comment]
I haven't been able to reproduce a problem with this link. It may be that it was impacted by other errors on the page that I've already fixed. Either way it is navigating to the `/users` page ok for me.
