### ISSUE TITLE
user rank shows same number for everyone

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#85]
![screenshot 2018-11-28 14 14 20](https://user-images.githubusercontent.com/1933118/49176040-f2511e80-f317-11e8-93da-2756d16f032c.png)

**Comment by alyssadelaine** [comment]
@scisco Is this still a problem after fixing https://github.com/developmentseed/scoreboard/issues/82 and https://github.com/developmentseed/scoreboard/issues/83?
