### ISSUE TITLE
Completeness section of campaigns is broken

### ISSUE THREAD

**Issue by scisco** [developmentseed/scoreboard#87]
![screenshot 2018-11-28 14 16 39](https://user-images.githubusercontent.com/1933118/49176177-3ba16e00-f318-11e8-9d85-990fc17e89c5.png)

**Comment by alyssadelaine** [comment]
@scisco I saw this error, but it went away when I refreshed my page

**Comment by scisco** [comment]
@sethvincent I think this is a general problem across the site where the styles are not loaded on first visit but will load on a refresh.
